### ISSUE TITLE
http.webdav doesn't work on armv7 

### ISSUE THREAD

**Issue by Rurik19** [hacdias/caddy-webdav#1]
Good afternoon!

I've installed caddy 0.10.4 with http.webdav on my armv7 server (cubietruck) and I have an error: 
` Parse error: Unknown directive 'webdav'`
caddyfile is:
```
files.domain.ru
basicauth /  login 123456
webdav / /media
```

**Comment by hacdias** [comment]
Hey @Rurik19! As it is stated on the [documentation](https://caddyserver.com/docs/http.webdav), "Currently not compatible with the build server. Don't download it.". It will only be available when Caddy 0.10.5 is out, unless you build Caddy from source of course. Sorry for the trouble 😞

**Comment by Rurik19** [comment]
http.filemanager doesn't work as well with similar error

**Comment by hacdias** [comment]
File Manager should work. Did you select http.filemanager on the [download page](https://caddyserver.com/download)?

**Comment by Rurik19** [comment]
Just reinstall and filemanager works now. Thank you!
Do you now when Caddy 0.10.5 is out?

**Comment by hacdias** [comment]
No problem 😄 Sorry for not having webdav working now though 😞
