### ISSUE TITLE
Is webdav HTTPS and SSL if available?

### ISSUE THREAD

**Issue by qdm12** [hacdias/caddy-webdav#11]
Hi there,

I am switching from SFTP to your webdav plugin for Caddy. Although it might be obvious, is your Webdav server plugin using the SSL connection of the domain name in which we add it in the Caddyfile ?

For example, my _Caddyfile_ is:
```
https://website.com {
    basicauth /myfiles user userpass
    webdav /webdav {
         scope /myfiles
    }
}
```
And I have SSL on with Caddy/Let's encrypt, will the webdav plugin use SSL?

Maybe add a little line about it on your readme 😃

**Comment by hacdias** [comment]
Yes, it will. Webdav uses HTTP so every layer you put on HTTP will also reflect on webdav.
