### ISSUE TITLE
Access using [webdav /webdav {}] prompts Method Not Allowed

### ISSUE THREAD

**Issue by ghost** [hacdias/caddy-webdav#12]
When configured like this, it is accessible:
[http://ip/webdav] Displays WebDAV normally.
```
:80/webdav {
	webdav / {
		scope /xxx
	}
}
```
This configuration is inaccessible:
[http: //ip/webdav] prompt Method Not Allowed.
```
:80 {
	webdav /webdav {
		scope /xxx
	}
}
```

What is the correct way to use [webdav /webdav {}]?

**Comment by makew0rld** [comment]
I am also experienced 405 Method Not Allowed for all methods that put files or folders, with the second configuration. The first config doesn't work at all though, likely due to #6

**Comment by hacdias** [comment]
Due to the recent developments of Caddy (v2!) and the incompatibility of this plugin with newer versions, as well as not being maintained, I'm closing this issue and archiving the repository.
