### ISSUE TITLE
Webdav should not scan folders recursively

### ISSUE THREAD

**Issue by oliwer** [hacdias/caddy-webdav#14]
I am trying to access my media library which contains a great number of files through webdav. It didn't work because I encountered issue #7, but this problem could be at least mitigated if the webdav server was not scanning folders recursively. In my case, when I GET / webdav tries to scan the whole partition!

I may have found the cause:
 - https://github.com/hacdias/webdav/blob/master/webdav.go#L59 When you receive a GET on a folder, you issue a PROPFIND request without setting the Depth header.
- https://github.com/golang/net/blob/master/webdav/webdav.go#L522 By default, Go's webdav module handles PROPFIND requests with infinite recursion. This could be avoided by setting the Depth header to 1 in the request.

**Comment by hacdias** [comment]
Will be fixed on the next release!
