### ISSUE TITLE
I can't seem to use webdav and filebrowser at the same time in the root of the site.

### ISSUE THREAD

**Issue by daiaji** [hacdias/caddy-webdav#15]
which will make webdav not work.
![48634725-37fd1580-ea01-11e8-8185-5be165bff808](https://user-images.githubusercontent.com/25875791/48655868-40cd0600-ea58-11e8-8651-502721680721.png)

```
(default) {
    gzip
    tls ****** {
        dns cloudflare
    }
}
*** {
    import default
    webdav {
        scope *
    }
    filemanager / *
}
```

**Comment by hacdias** [comment]
Due to the recent developments of Caddy (v2!) and the incompatibility of this plugin with newer versions, as well as not being maintained, I'm closing this issue and archiving the repository.
