### ISSUE TITLE
Secure Auth?

### ISSUE THREAD

**Issue by ghost** [hacdias/caddy-webdav#16]
Im speciifically wondering how do i disable Anon Login? Anybody right now can access and modify the files on my server

**Comment by Conor-Burns** [comment]
add basicauth by caddy or use another plugin like jwt and login

**Comment by hacdias** [comment]
@Zach-15803 heeey! You can just do what @Conor-Burns said 😄

**Comment by orangelynx** [comment]
just wondering: will jwt/login work with all apps that have a webdav api? I'm assuming that most webdav clients implement basic auth, so is jwt/login compatible with that?

(I hope I'm talking some sense, I'm not too familiar with webDAV and jwt stuff).

**Comment by hacdias** [comment]
Yes, most WebDAV clients rely on basic auth and not on jwt. I'm not aware of any clients that work with jwt.
