### ISSUE TITLE
Clarify Allow Deny options

### ISSUE THREAD

**Issue by orangelynx** [hacdias/caddy-webdav#18]
It is in general not quite clear how allow and deny and modify options interact with one another.

Assuming modify is true, all users will have access to all folders in the root. Allowing a certain subpath won't take effect. What if I deny /a but allow /a/b? What if modify is false?

What rule takes precedence?

**Comment by hacdias** [comment]
Hey @orangelynx! Sorry for taking so long replying. We test the rules from the latest to the first in the list. So the ones added latter would have higher precendence.

Let's say you have:

```
deny /a
alow /a/b
```

That will deny `/a`, except `/a/b`. 

The first rule that matches the current path, is the one that will be used, independently of being an `allow` or `deny` rule.
