### ISSUE TITLE
Documentation buglet

### ISSUE THREAD

**Issue by hartzell** [hacdias/caddy-webdav#19]
There's a bit of a bug on the documentation **at the Caddy website**, https://caddyserver.com/docs/http.webdav.

I filed an issue there (https://github.com/mholt/caddy/issues/2640), but @mholt closed it, pointing out that unsupported plugins aren't supported.

I pointed out, a second time, that the **typo is on the Caddy website**, not the plugin's GitHub site.  At that point he locked it.

So, perhaps you have control over what gets displayed on the Caddy site.  If so, there's a small confusing point that you might be able to fix.

If not, perhaps you can talk to @mholt about it.

---

The docs for http.dav on the website (https://caddyserver.com/docs/http.webdav) say this:

> ## Custom Scope
> ```
> webdav {
>       scope /
> }
> ```
> WebDAV on /admin for the whole file system.

which doesn't quite make sense.

The "Full documentation" (https://github.com/hacdias/caddy-webdav/blob/master/README.md) says this instead:

> ```
> webdav /admin {
>     scope /
> }
> ```

which makes more sense.

I think that there's a missing `/admin` in the example on the Caddy site.

**Comment by hacdias** [comment]
Thanks for the report. Fixed!

We, plugin authors, provide the documentation that appears on Caddy's website so it really is our responsibility to fix it 😃
