### ISSUE TITLE
Feature request: File permissions for users

### ISSUE THREAD

**Issue by Flameborn** [hacdias/caddy-webdav#2]
Hello,

When this middleware was part of Filemanager, one had the ability to fine-tune whether users can modify/delete files.

Would it be possible to add this back to this middleware and have read only access for authorised users?

**Comment by hacdias** [comment]
Hello @Flameborn! I can add it back then 😄 I didn't know if it was useful so I haven't added it.

**Comment by Flameborn** [comment]
Thank you 😂

It is definitely useful.

Also, the readme does not mention this, but does the block command support blocking DotFiles still?

**Comment by hacdias** [comment]
No 😂 I'll add that too

**Comment by Flameborn** [comment]
Huge thanks! 😂

**Comment by hacdias** [comment]
@Flameborn an `allow_edit` and `allow_new`? Or just `modify`?

**Comment by hacdias** [comment]
I decided creating a `modify`. If you think it would be better to split between edit and new, just tell me. I also added the 'magic' word `dotfiles`. 😄 Just check the README and tell me if you agree.

**Comment by Flameborn** [comment]
Thank you very much!

I am all for customisability, even though this current state suits my needs. If it's not too much work, you could probably split the two for a Create and Append, or just wait for a new issue which specifically requests it. I am personally happy with the way it works now.

Do you know if Caddy's build server will pick up the changes, or do I need to manually rebuild it with the Webdav middleware due to vendoring?

**Comment by hacdias** [comment]
Hello! I can create those but it's a bit ambiguous: Webdav uses PUT both
for creating and editing files so I won't know which permission to use
there - unless I check if the file exists.

This will only be available when Caddy 0.10.5 is out so you have to build
it manually for now. I think that the next revision of Caddy will soon be
out.

**Comment by Flameborn** [comment]
Hello,
Yes, unfortunately WebDav is not quite elegant in some aspects. If this is needed, one could always create a new issue or a PR.

The feature I requested works, so I consider this solved. Thank you very much!

**Comment by hacdias** [comment]
It is now available to download from the website :)

**Comment by Flameborn** [comment]
Great news, thank you very much!
