### ISSUE TITLE
Cannot list some files

### ISSUE THREAD

**Issue by Nomeji** [hacdias/caddy-webdav#22]
Sometimes directory listing stop and this error is displayed in caddy:

`http: superfluous response.WriteHeader call from golang.or
g/x/net/webdav.(*Handler).ServeHTTP (webdav.go:74)`

In Movian, it cannot show the full list of file in the folder. I can access some files, but some are also missing. I guess a specific file is creating this error and then every other file after this one is dismiss, unfortunately I cannot find witch one is it.

Same thing in gvfs but it doesn't display any file and show this error : "Sorry could not display all the contents of "folder": could not parse response".

Here is a example of files that caddy-webdav cannot list:

```
total 64
drwxr-xr-x   6 nomeji users  4096 Mar 23 14:55 AMV
drwxr-xr-x  15 nomeji users  4096 Jun  6 13:57 Animes
drwxr-xr-x   4 nomeji users  4096 Sep 11 10:58 Backup
drwxr-xr-x  17 nomeji users  4096 Sep 12 16:49 Films
drwxr-xr-x  10 nomeji users  4096 Apr  2 19:36 Images
drwxr-xr-x   6 nomeji users  4096 Jun  6 13:58 Jeux
drwxr-xr-x   3 nomeji users  4096 Jun  6 13:55 Logiciels
drwx------   2 root   root  16384 Mar  5  2015 lost+found
drwxr-xr-x 185 nomeji users 12288 Aug 19 10:14 Musiques
drwxr-xr-x   5 nomeji users  4096 Jun  6 13:54 Series
drwxr-xr-x   4 nomeji users  4096 Sep 13 13:15 tmp
```

I don't know witch of these folders throw the error.

I have other folders where I get the error but I don't want to share them.

As as workaround, I can access files further in the arborescent by specifying the exact path in my client.

Caddy v1.0.3 (h1:i9gRhBgvc5ifchwWtSe7pDpsdS9+Q0Rw9oYQmYUTw1w=)
Tested clients: Movian, gvfs

Please, help me create a reproducible test case for you.

**Comment by hacdias** [comment]
Due to the recent developments of Caddy (v2!) and the incompatibility of this plugin with newer versions, as well as not being maintained, I'm closing this issue and archiving the repository.
