### ISSUE TITLE
Can't upload any files

### ISSUE THREAD

**Issue by makew0rld** [hacdias/caddy-webdav#24]
Here is my Caddyfile:
```
DOMAIN.TLD {
    root /var/www
    browse /files
    gzip
    redir {
        [.....]
    }

    basicauth /joplin makeworld PASSWORD
    webdav /joplin {
        scope /home/makeworld/joplin
    }

}
```

Connecting to the server and listing the directory contents works, but any modification methods, such as MKCOL, RMCOL, MPUT, and DELETE, all return the error: 405 Method Not Allowed. Any idea why this is happening? I tested this with [cadaver](http://www.webdav.org/cadaver/).

**Comment by hacdias** [comment]
Weird... can you try adding `modify true` to the options of `webdav`? It should be true by default, but... we never know

**Comment by makew0rld** [comment]
I actually figured out the issue and worked around it, it was because of #6

**Comment by maxiride** [comment]
> 
> 
> I actually figured out the issue and worked around it, it was because of #6

I am encountering the same issue but I didn't understood exactly how #6 helped you solve the issue with Joplin. Could you please elaborate?

Also #12 seems a dead end.

I'd like to sync joplin using caddy's webdav which shouldn't be rocketscience ^^

**Comment by makew0rld** [comment]
@Maxiride I never truly fixed this :disappointed:. I don't remember what I was able to fix with #6, but in the end I reverse proxied [this](https://hub.docker.com/r/bytemark/webdav) docker WebDAV container instead. It runs WebDAV using Apache.

**Comment by maxiride** [comment]
Thanks for the update @makeworld-the-better-one, I was brainstorming a third party solution at this point and I will look into the container you suggested. Too bad we couldn't manage to keep everything in the caddy ecosystem.

**Comment by hacdias** [comment]
Due to the recent developments of Caddy (v2!) and the incompatibility of this plugin with newer versions, as well as not being maintained, I'm closing this issue and archiving the repository.
