### ISSUE TITLE
OPTIONS 404 

### ISSUE THREAD

**Issue by Rurik19** [hacdias/caddy-webdav#3]
@hacdias it seems that it doesn't work. i get
```
ip - - [28/Jul/2017:12:50:43 +0500] "OPTIONS / HTTP/1.1" 404 14
```
in log
caddy 0.10.6, armv7, caddyfile is:
```
files.domain.ru
basicauth /  login 123456
webdav /media
```

**Comment by hacdias** [comment]
You're request seems to be for "/". It should be for /media.  The first WebDAV parameter is the url.

**Comment by Rurik19** [comment]
the same result
```
[30/Jul/2017:22:59:40 +0500] "OPTIONS /media HTTP/1.1" 404 14
```

**Comment by Rurik19** [comment]
I understand now. I mean `media` as scope, but scope must be set only by 'scope' directive.

**Comment by hacdias** [comment]
Exactly 😄
