### ISSUE TITLE
no action found for directive 'webdav' with server type 'http' (missing a plugin?)

### ISSUE THREAD

**Issue by davidv171** [hacdias/caddy-webdav#30]
I installed caddy using: 
curl https://getcaddy.com | bash -s personal tls.dns.cloudflare http.webdav

And I'm using

```
 webdav / {
   scope ./Website/Pictures
}
```

As the only relevant config.

**Comment by hacdias** [comment]
Due to the recent developments of Caddy (v2!) and the incompatibility of this plugin with newer versions, as well as not being maintained, I'm closing this issue and archiving the repository.
