### ISSUE TITLE
Caddy-WebDav has a reference to the current directory in its listing when used via WinSCP

### ISSUE THREAD

**Issue by Flameborn** [hacdias/caddy-webdav#4]
Hello,

When Caddy-WebDav is used with WinSCP as the client, every directory, except for the root one has a bogus directory with the same name as the current directory when listing its contents.

For example, _domain.com/dav/audio_ has a non-existing _audio_ directory, and when downloading the directory contents, WinSCP tries to access _domain.com/dav/audio/audio_, as well.

Total Commander's WebDav plugin works, while CarrotDav (does not honour /path/ and tries domain.com/resourceName instead), Cadaver (Did not find a collection resource.) and LFTP (405 Method Not Allowed (HEAD)) are unable to access any WebDav resource, so unfortunately I was not able to test this further.

**Comment by Flameborn** [comment]
To add to this, the bogus directory issue only seems to happen when Caddy-Webdav is active for something other than the root, e.g.,  _webdav /dav {_

**Comment by hacdias** [comment]
I'll check this out as soon as I can. Thanks for reporting!
