### ISSUE TITLE
Possibly incompatible with caddy site paths

### ISSUE THREAD

**Issue by dhaavi** [hacdias/caddy-webdav#6]
Webdav works perfectly with this Caddyfile:

    localhost {

      webdav /webdav {
        scope .
      }

    }

However, it does not with this one:

    localhost/webdav {

      webdav / {
        scope .
      }

    }

Tested with:

[cadaver](http://www.webdav.org/cadaver/) 0.23.3, responds with:

    Could not access /webdav/ (not WebDAV-enabled?):
    Did not find a collection resource.

[nautilus](https://wiki.gnome.org/Apps/Nautilus) 3.14.3, responds with:

    Unhandled error message: Not a WebDAV enabled share

Sorry for the simple issue. I'll gladly do more testing and look into the source myself later.

**Comment by hacdias** [comment]
~Yes, it is incompatible right now with that. I'll solve it as soon as I can!~ It is working here... I'll investigate

**Comment by dhaavi** [comment]
I figured the problem is the client software and that it fails when the path is modified during transit by caddy. I created a PR for caddy (https://github.com/mholt/caddy/pull/1959) to turn off path trimming with a plugin.
@mholt suggested to fix this problem here instead.
What are your thoughts?

**Comment by hacdias** [comment]
Hello @dhaavi! Yes, could you open a PR here with the fix? 😄

**Comment by maxiride** [comment]
Is there any workaround on this issue?
I haven't been able to use the webdav plugin at all so far. Nor with cadaver, nor Joplin or any other client.

**Comment by hacdias** [comment]
Due to the recent developments of Caddy (v2!) and the incompatibility of this plugin with newer versions, as well as not being maintained, I'm closing this issue and archiving the repository.
